### ISSUE TITLE
Store matrix id and make opt-out possible [tchapbot, backend] 

### ISSUE THREAD

**Issue by pedevineau** [etalab-ia/albert-tchap#14]
- Read matrix id in Tchapbot API and send it to the Albert API backend
- Change the backend users model OR create another tchap_users model, where a user is identified by its matrix_id
- OPTOUT Add a command !reset in tchap and a backend endpoint to delete all logs linked to a matrix_id

**Comment by dtrckd** [comment]
Logs won't be saved anymore in v0.2. I am closing it.
