### ISSUE TITLE
Create a pending chat request list instead of "join on invite" logic

### ISSUE THREAD

**Issue by bolinocroustibat** [etalab-ia/albert-tchap#54]
Right now, when `join_on_invite` is set to False, the user send a message but doesn't receive any answer while he's waiting for the bot to accept teh invitation and join the salon.
It's quite confusing in terms of UX.

We can replace that logic with a pending request file stored in local volume, listing the users IDs which have pending requests not yet accepted. If it's in the pending list, the bot should reply to message "Wait for your user to be accepted blah blah blah" but shouldn't interact at all except for that.

**Comment by bolinocroustibat** [comment]
PR: https://github.com/etalab-ia/albert-tchapbot/compare/feat/users-whitelist?expand=1

**Comment by dtrckd** [comment]
fixed in #75
