### ISSUE TITLE
Create aliases commands

### ISSUE THREAD

**Issue by bolinocroustibat** [etalab-ia/albert-tchap#56]
For example, we should have the `!help` alias for `!aide`

**Comment by bolinocroustibat** [comment]
PR: https://github.com/etalab-ia/albert-tchapbot/pull/58

**Comment by bolinocroustibat** [comment]
https://github.com/etalab-ia/albert-tchapbot/pull/61

**Comment by dtrckd** [comment]
Done in v0.2.
