### ISSUE TITLE
Use a size/time limit for conversation?

### ISSUE THREAD

**Issue by dtrckd** [etalab-ia/albert-tchap#6]
**Context:** forever growing chat conversation  

**Problem:** too large history can cause model misbehavior problems

As a temporary solution, waiting for models to better handle long conversations (like auto-synthesis/compression), one could set a hard limit for conversation. Ie the model will only have access to the last N messages in the chat history.

**Comment by bolinocroustibat** [comment]
How can we count and store the number of message in chat history on Tchapbot'side? Does the API send back some stream number for a given chat?

**Comment by dtrckd** [comment]
we do not count, but the history size could be fetched from an API request.

**Comment by dtrckd** [comment]
I think we should introduce a "forget factor" that depends on distance between the last user message and the current one that will determine the size of the historize size, given that we should have an upper limit (that ideally depends on the max_tokens of the model), and size zero when the distance is greater than X hours. I am going to propose PR about it.

**Comment by bolinocroustibat** [comment]
> We do not count, but the history size could be fetched from an API request.
That works. Makes another request though. Could we send back the stream number as a response in the existing request instead? Or does that makes the API even further away from OpenAI standards?

**Comment by bolinocroustibat** [comment]
> I think we should introduce a "forget factor" that depends on the duration between the last user message and the current one that will determine the size of the history, given that we should have an upper limit (that will ideally depends on the max_tokens of the model), and with zero size when the distance is greater than X hours. I am going to propose PR about it.

You mean, time-based. Yes, that's a good idea. It does not always solve the issue of size being too big though, if the user chats a lot and quickly within the time frame, is it?

**Comment by dtrckd** [comment]
> > We do not count, but the history size could be fetched from an API request.
> 
> That works. It makes another request though. Could we send back the stream number as a response in the existing request instead? Or does that makes the API even further away from OpenAI standards?

What do you mean "stream number" ?


> You mean, time-based. Yes, that's a good idea. It does not always solve the issue of size being too big though, if the user chats a lot and quickly within the time frame, is it?

That is why I say a thing about an "upper limit". The maximum size of the history the model can handle. It depends of the context window, though the model in used.

**Comment by bolinocroustibat** [comment]
> What do you mean "stream number" ?
The stream count in the chat, in the case when the limit would be based on the number of streams.

**Comment by dtrckd** [comment]
> > What do you mean "stream number" ?
> 
> The stream count in the chat, in the case where the limit would be based on the number of streams.

Yes, we could pass an history size limit as a parameter (and fix a hard limit by default as well)

**Comment by bolinocroustibat** [comment]
> That's why I call it an "upper limit". This is the maximum history size that the model can handle. It depends on the context window, i.e. the model used.

Nee to chat about that to be sure I understand, but anyway the idea of forgetting / resetting a new chat after some time is good in terms of UX.

**Comment by bolinocroustibat** [comment]
Changing this priority to priority 1, as our data scientists recommended to have a shorter history for llama-3 based models and that it would explain some currently bad results.

**Comment by bolinocroustibat** [comment]
@dtrckd The timer rest feature has been done :
https://github.com/etalab-ia/albert-tchapbot/commit/f4fb701358017f7dd81d736bc5cd34d2d4f375ee
https://github.com/etalab-ia/albert-tchapbot/commit/8071ea8e17a08a2d7da25131806b696f630d37e2

**Comment by dtrckd** [comment]
A max_rewind settings has been add to cap the history size of the conversation.
Done in v0.2
