### ISSUE TITLE
[UX] Don't display the reset message, if the conversation is already reset.

### ISSUE THREAD

**Issue by dtrckd** [etalab-ia/albert-tchap#66]
Here is a scenario that exemplify the behavior: 

1. If you type !reset
2. and then a ask a question
3. the bot answer that as it is a long time that I haven't discuss with him, and that he reset my conversation. it's confusing as I just reset the conversation already.

**Comment by bolinocroustibat** [comment]
This should do the trick: https://github.com/etalab-ia/albert-tchap/pull/67
