### ISSUE TITLE
 add  "-v" option to the !help command

### ISSUE THREAD

**Issue by dtrckd** [etalab-ia/albert-tchap#69]
Proposition : 

- add option "-v" to the !help command to show the full list of commands (included hidden one).  This can be useful to access the full doc for user that have some knowledge.

**Comment by EstelleHary** [comment]
Good idea, it allows to have two information layers. Before implementing it though we need to check what are all the information we have to bring to the user and then we'll see how it works with what you propose here.

**Comment by dtrckd** [comment]
done in v0.2 (it's for geek!)
